sudo: required   // we need super level
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t bunta1974/docker-react .

script:
  - docker run bunta1974/docker-react npm run test -- --coverage
